# Generated by Django 2.2.6 on 2020-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='crc',
            field=models.CharField(db_index=True, editable=False, max_length=32, verbose_name='CRC'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Size'),
        ),
    ]
