# Generated by Django 2.2.6 on 2020-10-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201022_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='crc',
            field=models.UUIDField(editable=False, unique=True, verbose_name='CRC'),
        ),
    ]
