# Generated by Django 2.2.6 on 2020-10-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Name')),
                ('fullname', models.CharField(db_index=True, max_length=64, verbose_name='Full name')),
            ],
            options={
                'verbose_name': 'Document type',
                'verbose_name_plural': 'Document types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Short name')),
                ('fullname', models.CharField(db_index=True, max_length=64, verbose_name='Full name')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.File', verbose_name='File')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('comments', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Comments')),
                ('doctype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctype_document', to='shipment.DocType', verbose_name='DocType')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_document', to='shipment.Org', verbose_name='Customer')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_document', to='shipment.Shipper', verbose_name='Shipper')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('date', 'shipper', 'org'),
            },
        ),
    ]
