# Generated by Django 2.2.6 on 2020-10-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='fullname',
            field=models.CharField(db_index=True, max_length=64, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.File', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='org',
            name='fullname',
            field=models.CharField(db_index=True, max_length=64, null=True, verbose_name='Full name'),
        ),
    ]
