# Generated by Django 3.0.10 on 2020-11-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20201022_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-date', 'shipper', 'org'), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='doctype',
            name='fullname',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctype_document', to='shipment.DocType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='org',
            name='fullname',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Full name'),
        ),
    ]
